# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
dist: xenial
language: python
# virtualenv:
#  system_site_packages: true
matrix:
  include:
    - os: linux
      python: 3.4
      env: TOXARGS="-e py34,lint" DISTRIB="ubuntu" COVERAGE="false"
    - os: linux
      python: 3.7
      env: TOXARGS="-e py37,lint" DISTRIB="ubuntu" COVERAGE="true"
install:
  - source tests/travis_install.sh
  - travis_retry pip install pip setuptools --upgrade
  - travis_retry pip install tox
  - if [[ "$COVERAGE" == "true" ]]; then travis_retry pip install coveralls; fi
  # ^  DEPRECATION WARNING:
  # The automatic creation of a `requirements.txt` file is deprecated.
  # See `Dependency Management` in the docs for other options.
before_script:
  # - git config --global user.email "you@example.com"
  # - git config --global user.name "Your Name"
  - rm -rf .coverage
  - python --version
  - pip --version
  - pip freeze
script:
  # - python setup.py test
  # ^  Change here if using tox
  - tox $TOXARGS
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
